framework:
    messenger:
        failure_transport: failed

        buses:
            messenger.bus.default:
                middleware:
                    - doctrine_transaction

        transports:
            async: '%env(MESSENGER_TRANSPORT_DSN)%'
            sync: 'in-memory://'
            failed:
                dsn: 'doctrine://default?queue_name=failed'
            scheduler_partitions:
                dsn: 'doctrine://default?queue_name=scheduler_partitions'
            scheduler_clear_bot_messages:
                dsn: 'doctrine://default?queue_name=scheduler_clear_bot_messages'

        routing:
            'App\Infrastructure\Scheduler\Common\RefreshDbPartitionsMessage': scheduler_partitions
            'App\Infrastructure\Scheduler\Telegram\ClearBotMessagesMessage': scheduler_clear_bot_messages
