# Production environment override
services:
  app:
    build:
      context: ./docker/php
      target: php_dev
      args:
        APP_PORT: ${APP_PORT}
        TIMEZONE: ${TIMEZONE}
        COMPOSER_VERSION: ${COMPOSER_VERSION}

  supervisor:
    build:
      context: ./docker/php
      target: php_dev_supervisor
      args:
        APP_PORT: ${APP_PORT}
        TIMEZONE: ${TIMEZONE}
        COMPOSER_VERSION: ${COMPOSER_VERSION}

  nginx:
    build:
      context: ./docker/nginx

  frontend:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
      target: node_dev
      args:
        - VITE_API_URL=${VITE_API_URL}
    ports: []
