# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
imports:
    - { resource: 'components/common.yaml' }
    - { resource: 'components/telegram.yaml' }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.env: '%env(APP_ENV)%'
    app.name: '%env(APP_NAME)%'
    app.version: '%env(APP_VERSION)%'
    app.secret: '%env(APP_SECRET)%'
    scheduler.timezone: 'UTC'
services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            string $botName: '%telegram.bot_name%'
            string $botToken: '%telegram.bot_token%'
            string $apiUrl: '%telegram.api_url%'
            string $appSecret: '%app.secret%'

    _instanceof:
        App\Infrastructure\Telegram\Routing\Registry\RouteRegistryInterface:
            tags: ['telegram.route_registry']

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Kernel.php'
            - '../src/Component/*/*/Entity/'
            - '../src/Component/*/*/UseCase/'
            - '../src/Component/*/*/ValueObject/'
            - '../src/Domain/*/Entity/'
            - '../src/Domain/*/Enum/'
            - '../src/Domain/*/ValueObject/'
            - '../src/Application/Command/'

    Psr\Container\ContainerInterface: '@service_container'

    App\Application\Handler\:
        resource: '../src/Application/Handler'
        public: true

    App\Infrastructure\Telegram\Routing\Router:
        arguments:
            $botName: '%telegram.bot_name%'
            $registries: !tagged_iterator telegram.route_registry

    App\Infrastructure\Telegram\Middleware\MiddlewareManager:
        arguments:
            $middlewares:
                - '@App\Infrastructure\Telegram\Middleware\DeduplicationMiddleware'
                - '@App\Infrastructure\Telegram\Middleware\ChatPersistenceMiddleware'
